### ISSUE TITLE
Deprecation: Promise.allSettled native implementation with less overhead

### ISSUE THREAD

**Issue by wzhouwzhou** [OsoianMarcel/promise-all-always#2]
In reference to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled, it looks like we're now all set in terms of allSettled making its way into the spec. Would either consider deprecating this package and directing people to use the built-in method without unnecessary overhead or third party bloat, or to specifically check for polyfill and prominently note on the Readme so as not to mislead developers. There are no features in this library that cannot be solved with a simple await and clean `.map(e => e.value ?? e.reason)` rather than 50+ lines of bloat.

**Comment by OsoianMarcel** [comment]
https://github.com/OsoianMarcel/promise-all-always/commit/8c656c40ab6a4ec13298067e992d5c2ddbcf2cb3
